[package]
name = "ezkl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
synthetic_data = { path = "../synthetic_data" }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.11.0-pre.5"
hex = "0.4"

[dev-dependencies]

